version: "3.9"

services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    hostname: mysql
    networks:
      - discord-tickets
    volumes:
      - tickets-mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}

  bot:
    image: eartharoid/discord-tickets:4.0
    depends_on:
      - mysql
    restart: unless-stopped
    hostname: bot
    networks:
      - discord-tickets
    ports:
      - 8169:8169
    volumes:
      - tickets-bot:/home/container/user
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    tty: true
    stdin_open: true
    # Please refer to the documentation:
    # https://discordtickets.app/self-hosting/configuration/#environment-variables
    environment:
      DB_CONNECTION_URL: ${DB_CONNECTION_URL}
      DISABLE_ENCRYPTION: ${DISABLE_ENCRYPTION}
      DISCORD_SECRET: ${DISCORD_SECRET}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      DB_PROVIDER: ${DB_PROVIDER}
      HTTP_EXTERNAL: ${HTTP_EXTERNAL}
      HTTP_HOST: ${HTTP_HOST}
      HTTP_INTERNAL: ${HTTP_INTERNAL}
      HTTP_PORT: ${HTTP_PORT}
      HTTP_TRUST_PROXY: ${HTTP_TRUST_PROXY}
      INVALIDATE_TOKENS: ${INVALIDATE_TOKENS}
      OVERRIDE_ARCHIVE: ${OVERRIDE_ARCHIVE}
      PUBLIC_BOT: ${PUBLIC_BOT}
      PUBLISH_COMMANDS: ${PUBLISH_COMMANDS}
      SUPER: ${SUPER}

networks:
  discord-tickets:

volumes:
  tickets-mysql:
  tickets-bot:
